module.exports={
    Admin: [
        "/items/add",
        "/items/delete/:id",
        "/lostobjects/add", 
        "/lostobjects/edit/:id", 
        "/lostobjects/delete/:id",
        "/reports/add",
        "/reports/edit/:id",
        "/reports/delete/:id",
        "/reservations/all",
        "/reservations/takenow/:id",
        "/reservations/add",
        "/reservations/return/:id",
        "/reservations/edit/:id",
        "/reservations/delete/:id"
    ],
    User: [
        "/lostobjects/add", 
        "/lostobjects/edit/:id", 
        "/lostobjects/delete/:id",
        "/reports/add",
        "/reports/edit/:id",
        "/reports/delete/:id",
        "/reservations/all",
        "/reservations/takenow/:id",
        "/reservations/add",
        "/reservations/return/:id",
        "/reservations/edit/:id",
        "/reservations/delete/:id"
    ]
}